services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: brainer-postgres
    environment:
      POSTGRES_DB: brainer
      POSTGRES_USER: brainer
      POSTGRES_PASSWORD: brainer_password_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brainer -d brainer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 